"""initial schema1

Revision ID: 2951f1f18431
Revises: 
Create Date: 2025-08-28 20:44:10.158879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2951f1f18431'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('inventory_reduced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('confirmation_sent')
        batch_op.drop_column('inventory_reduced')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
